[package]
name = "fractol_rust"
version = "0.0.2"
authors = ["Arthur <awoimbee@student.42.fr>"]
edition = "2018"

[dependencies]
vulkano-win = "0.11"
winit = "0.18"
vulkano = "0.11"
vulkano-shaders = "0.11"
image = "0.19"
