[package]
name = "rustcraft"
version = "0.0.1"
authors = ["Arthur W. <arthur.woimbee@gmail.com>"]
edition = "2018"

[dependencies]
vulkano-shaders = "0.14.0"
vulkano-win =     "0.14.0"
vulkano =         "0.14.0"
bitfield =        "0.13.2"
winit =           "0.19.3"
